#!/bin/sh
# postinst script for flexibee-contract-invoices

set -e

    if [ "$1" = "configure" ]; then

    . /usr/share/debconf/confmodule

    fi

db_get composer/WEB_USER
WEBUSER=$RET

mkdir -p /var/lib/composer /var/lib/flexibee-contract-invoices   
chown $WEBUSER:$WEBUSER /var/lib/composer /var/lib/flexibee-contract-invoices /usr/lib/flexibee-contract-invoices/ -R
su - $WEBUSER -s /bin/bash -c 'COMPOSER_HOME="/var/lib/composer" composer --no-dev -o install -d /usr/lib/flexibee-contract-invoices/'

#DEBHELPER#

exit 0
